import "./globals.css";
import { ThemeProvider } from "@/providers/theme-providers";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import type { Metadata } from "next";
import { ToasterProvider } from "@/providers/toast-providers";
export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by pintas",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ToasterProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
